# 
# Synthesis run script generated by Vivado
# 

set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.cache/wt [current_project]
set_property parent.project_path D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci
set_property is_locked true [get_files d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1 -new_name fifo_512x8 -ip [get_ips fifo_512x8]]

if { $cached_ip eq {} } {

synth_design -top fifo_512x8 -part xc7a35ticsg324-1L -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix fifo_512x8_ fifo_512x8.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_512x8_stub.v
 lappend ipCachedFiles fifo_512x8_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_512x8_stub.vhdl
 lappend ipCachedFiles fifo_512x8_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_512x8_sim_netlist.v
 lappend ipCachedFiles fifo_512x8_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_512x8_sim_netlist.vhdl
 lappend ipCachedFiles fifo_512x8_sim_netlist.vhdl

 config_ip_cache -add -dcp fifo_512x8.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips fifo_512x8]
}

rename_ref -prefix_all fifo_512x8_

write_checkpoint -force -noxdef fifo_512x8.dcp

catch { report_utilization -file fifo_512x8_utilization_synth.rpt -pb fifo_512x8_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


}; # end if cached_ip 

add_files D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_stub.v -of_objects [get_files d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci]

add_files D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_stub.vhdl -of_objects [get_files d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci]

add_files D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_sim_netlist.v -of_objects [get_files d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci]

add_files D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_sim_netlist.vhdl -of_objects [get_files d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci]

add_files D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8.dcp -of_objects [get_files d:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/fifo_512x8/fifo_512x8.xci]

if {[file isdir D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8]} {
  catch { 
    file copy -force D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_sim_netlist.v D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8
  }
}

if {[file isdir D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8]} {
  catch { 
    file copy -force D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_sim_netlist.vhdl D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8
  }
}

if {[file isdir D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8]} {
  catch { 
    file copy -force D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_stub.v D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8
  }
}

if {[file isdir D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8]} {
  catch { 
    file copy -force D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/managed_ip_project/managed_ip_project.runs/fifo_512x8_synth_1/fifo_512x8_stub.vhdl D:/Mike/themes/FPGA/work/ip_lib/fifo_512x8/ip_user_files/ip/fifo_512x8
  }
}
