# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Mike/themes/FPGA/work/ip_lib/fifo_256x8/fifo_256x8/fifo_256x8.xci
# IP: The module: 'fifo_256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mike/themes/FPGA/work/ip_lib/fifo_256x8/fifo_256x8/fifo_256x8/fifo_256x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Mike/themes/FPGA/work/ip_lib/fifo_256x8/fifo_256x8/fifo_256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Mike/themes/FPGA/work/ip_lib/fifo_256x8/fifo_256x8/fifo_256x8.xci
# IP: The module: 'fifo_256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mike/themes/FPGA/work/ip_lib/fifo_256x8/fifo_256x8/fifo_256x8/fifo_256x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Mike/themes/FPGA/work/ip_lib/fifo_256x8/fifo_256x8/fifo_256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
